{% set name = "split-query" %}
{% set version = "0.2.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "aa6587d0cfbbca36b3ea08fcd743134c6b9b05f07ac7bde028e3fd9fa11ade7c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - appdirs
    - python
    - future
    - iso8601
    - pandas
    - pytables          # Named tables on PyPI and in source.
    - pytz
    - sympy

test:
  imports:
    - split_query
    - split_query.core
    - split_query.cache
    - split_query.decorators
    - split_query.engine
    - split_query.interface
    - split_query.remote

about:
  home: https://github.com/simonbowly/split-query
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: Tools for breaking up queries for caching, processing, etc.
  description: 'Split-Query

    ================


    Tools for breaking up queries for caching, processing, etc.'
  doc_url: ''
  dev_url: https://github.com/simonbowly/split-query

extra:
  recipe-maintainers:
    - simonbowly
