{% set name = "split-query" %}
{% set version = "0.2.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4fed2ff9e2ecdcd35ea684e17df337999ffd3232eebd05cab083d2f9b12aa682" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - appdirs
    - python
    - future
    - iso8601
    - pandas
    - pytables          # Named tables on PyPI and in source.
    - pytz
    - sympy

test:
  imports:
    - split_query
    - split_query.core
    - split_query.core.domain
    - split_query.core.expand
    - split_query.core.expressions
    - split_query.core.logic
    - split_query.core.serialise
    - split_query.core.wrappers
    - split_query.cache
    - split_query.decorators
    - split_query.engine
    - split_query.extract
    - split_query.interface

about:
  home: https://github.com/simonbowly/split-query
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: Tools for breaking up queries for caching, processing, etc.
  description: 'Split-Query

    ================


    Tools for breaking up queries for caching, processing, etc.'
  doc_url: ''
  dev_url: https://github.com/simonbowly/split-query

extra:
  recipe-maintainers:
    - simonbowly
