{% set name = "split-query" %}
{% set version = "0.2.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "7c2c324f192cbfa8ab04372ff99bf04b21ac38ad135fb758a94158ddfbccd8bd" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python
    - frozendict        # Requires conda-forge channel.
    - future
    - iso8601
    - msgpack-python
    - pandas
    - pytables          # Named tables on PyPI and for import.
    - pytz
    - sympy

test:
  imports:
    - split_query
    - split_query.core

about:
  home: https://github.com/simonbowly/split-query
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: Tools for breaking up queries for caching, processing, etc.
  description: 'Split-Query

    ================


    Tools for breaking up queries for caching, processing, etc.'
  doc_url: ''
  dev_url: https://github.com/simonbowly/split-query

extra:
  recipe-maintainers:
    - simonbowly
